export const sampleBooks = [
    {
      id: 1,
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      description: "A story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.",
      coverImage: "https://covers.openlibrary.org/b/id/10692641-L.jpg", 
    },
    {
      id: 2,
      title: "To Kill a Mockingbird",
      author: "Harper Lee",
      description: "A novel set in the American South during the 1930s, dealing with the issues of race and morality.",
      coverImage: "https://covers.openlibrary.org/b/id/10692642-L.jpg", 
    },
    {
      id: 3,
      title: "1984",
      author: "George Orwell",
      description: "A dystopian novel set in a totalitarian society ruled by the Party and its leader, Big Brother.",
      coverImage: "https://covers.openlibrary.org/b/id/7222246-L.jpg", 
    },
    {
      id: 4,
      title: "Pride and Prejudice",
      author: "Jane Austen",
      description: "A romantic novel of manners that follows the character development of Elizabeth Bennet.",
      coverImage: "https://covers.openlibrary.org/b/id/10692643-L.jpg", 
    },
    {
      id: 5,
      title: "The Catcher in the Rye",
      author: "J.D. Salinger",
      description: "A story about Holden Caulfield's experiences in New York City after being expelled from prep school.",
      coverImage: "https://covers.openlibrary.org/b/id/10692644-L.jpg", 
    },
    {
      id: 6,
      title: "Moby-Dick",
      author: "Herman Melville",
      description: "The voyage of the whaling ship Pequod, commanded by Captain Ahab, who seeks revenge on the white whale Moby-Dick.",
      coverImage: "https://covers.openlibrary.org/b/id/10692645-L.jpg", 
    },
    {
      id: 7,
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      description: "A fantasy novel about the adventures of Bilbo Baggins, a hobbit, who sets out on a quest to win a share of treasure guarded by a dragon.",
      coverImage: "https://covers.openlibrary.org/b/id/10692646-L.jpg", 
    },
    {
      id: 8,
      title: "Brave New World",
      author: "Aldous Huxley",
      description: "A dystopian novel set in a futuristic society where people are genetically engineered and conditioned for their roles in life.",
      coverImage: "https://covers.openlibrary.org/b/id/10692647-L.jpg", 
    },
    {
      id: 9,
      title: "The Lord of the Rings",
      author: "J.R.R. Tolkien",
      description: "An epic high-fantasy novel about the struggle to destroy the One Ring and defeat the Dark Lord Sauron.",
      coverImage: "https://covers.openlibrary.org/b/id/10692648-L.jpg", 
    },
    {
      id: 10,
      title: "Harry Potter and the Philosopher's Stone",
      author: "J.K. Rowling",
      description: "The first book in the Harry Potter series, following the adventures of a young wizard, Harry Potter, and his friends at Hogwarts School of Witchcraft and Wizardry.",
      coverImage: "https://covers.openlibrary.org/b/id/10692649-L.jpg", 
    },
  ];